model:
  hidden_channels: 256
  encoder:
    name: hierGT
    hidden_channels: 256
    edge_channels: 64
    key_channels: 128
    num_heads: 4
    num_interactions: 6
    cutoff: 10.0
    knn: 32
    num_filters: 128

sample:
  seed: 2025
  batch_size: 8
